# Generated by Django 3.1 on 2020-08-31 07:13

from django.db import migrations
from django.db import transaction

from bench.models import Chair


def create_chairs(*args, **kwargs):
    """
    Just make some chairs.
    """
    values = [
        {
            'name': 'Sofa',
            'sittability': 8,
            'kind': Chair.COUCH,
            'is_soft': True
        },
        {
            'name': 'Mememan\'s Chair',
            'sittability': 10,
            'kind': Chair.ASCENDED,
            'is_soft': True
        },
        {
            'name': 'Gaming Chair',
            'sittability': 9,
            'kind': Chair.IMMORTAL,
            'is_soft': True
        },
        {
            'name': 'CHAD Chair',
            'sittability': 7,
            'kind': Chair.STEEL,
            'is_soft': False
        },
        {
            'name': 'Elf Chair',
            'sittability': 8,
            'kind': Chair.WOOD,
            'is_soft': False
        }
    ]

    for value in values:
        with transaction.atomic():
            chair = Chair()
            chair.name = value['name']
            chair.sittabilitiy = value['sittability']
            chair.kind = value['kind']
            chair.is_soft = value['is_soft']
            chair.save()


def reverse_func(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_chairs, reverse_func)
    ]
